# This action packages the complete Zeebe distribution artifacts. This includes the Go client,
# zbctl, and the Zeebe distribution TAR ball. This excludes the Docker image. See the build-docker
# for that.

---
name: Build Zeebe
description: Builds & installs the complete Zeebe distribution

inputs:
  go:
    description: If false, will not build zbctl; defaults to true
    default: "true"
    required: false
  java:
    description: If false, will not build the Java distribution; defaults to true
    default: "true"
    required: false
  maven-extra-args:
    description: Additional CLI arguments which will be passed to the maven install command as is, e.g. "-am -pl util/"
    default: ""
    required: false

outputs:
  distball:
    description: "The path to the Zeebe distribution TAR ball"
    value: ${{ steps.build-java.outputs.result }}

runs:
  using: composite
  steps:
    - if: ${{ inputs.go == 'true' }}
      name: Build Go
      shell: bash
      id: build-go
      working-directory: clients/go/cmd/zbctl
      run: ./build.sh
    - if: ${{ inputs.java == 'true' }}
      name: Package Zeebe
      shell: bash
      id: build-java
      # we do not build in parallel to avoid memory and cache corruption issues, notably observed
      # on macOS and Windows
      run: |
        mvn -B -DskipTests -DskipChecks install ${{ inputs.maven-extra-args }}
        export BUILD_DIR=$(mvn -pl dist/ help:evaluate -Dexpression=project.build.directory -q -DforceStdout)
        export ARTIFACT=$(mvn -pl dist/ help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
        echo "::set-output name=result::${BUILD_DIR}/${ARTIFACT}.tar.gz"
