---
name: Use CI Nexus cache

description: Sets up use of co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml.

inputs:
  # Using an input with a default value as raw string here instead of relying on secrets.VAULT_ADDR
  # since workflows accessing any GHA secret cannot be run for PRs from outside contributors anymore,
  # see also https://github.com/camunda/zeebe/pull/9302#issuecomment-1118971782
  vault-url:
    description: 'Vault URL to use.'
    default: 'https://vault.int.camunda.com'

runs:
  using: composite
  steps:
  - name: Create ~/.m2/settings.xml with cache configuration
    shell: bash
    run: |
      cat <<EOF > ~/.m2/settings.xml
      <?xml version="1.0" encoding="UTF-8"?>
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
        <interactiveMode>false</interactiveMode>
        <servers>
          <server>
            <id>camunda-nexus</id>
            <username>\${env.NEXUS_USERNAME}</username>
            <password>\${env.NEXUS_PASSWORD}</password>
          </server>
        </servers>
        <mirrors>
          <mirror>
            <id>camunda-nexus</id>
            <mirrorOf>*</mirrorOf>
            <name>Camunda Nexus</name>
            <url>http://repository-ci-camunda-cloud.nexus:8081/content/groups/internal/</url>
          </mirror>
        </mirrors>
      </settings>
      EOF

  - name: Import Secrets
    uses: hashicorp/vault-action@v2.4.0
    with:
      url: "${{ inputs.vault-url }}"
      method: kubernetes
      path: kubernetes-camunda-ci
      role: gha-runner-camunda-agent # needs to align with namespace and serviceaccount name of the runner pod
      exportEnv: true
      secrets: |
        secret/data/k8s-camunda-ci/gha-runner-camunda/agent NEXUS_USERNAME;
        secret/data/k8s-camunda-ci/gha-runner-camunda/agent NEXUS_PASSWORD;
